### ISSUE TITLE
[Feature Request] Add options "Follow this profile"

### ISSUE THREAD

**Issue by NelsonRodMar** [jelilat/lensdrop#11]
A new option called "Follow this profile" (or a better name) would be cool to add for a cross giveaway/airdrop.
The requirement is that the user needs to follow a specific profile.
I got this in mind because I want to make a giveaway and ask people to follow also another profile; since I got a big audience this could boost another profile.
I will develop this by myself and make a PR in the future, but let me know what you think of this idea.

**Comment by jelilat** [comment]
Great request

This is actually in the roadmap and it’s currently being worked on. Should have a PR for this today
