### ISSUE TITLE
[Bug] No recipient found when using the home page for the drop on the post 0xac-0xb3 

### ISSUE THREAD

**Issue by dydymoon** [jelilat/lensdrop#13]
I did an airdrop of 2500 ERC20 tokens after 24h with the following restrictions: Follow me, Like, Mirror, Collect and Comment the post. 

On the home page, where it's possible to select the token address and amount / winner (I guess to send it directly), there was no recipient found 
![image](https://user-images.githubusercontent.com/69637819/202902691-7799c835-b0a0-4ed4-8735-28e30ab016e3.png)

I did it again on the followers page and it worked but it's not possible to select the token address and amount / winner , so I posted this one and I'll send the tokens manually 

![image](https://user-images.githubusercontent.com/69637819/202902759-9412d7d9-3c17-44b2-8ef0-efe0c240a97c.png)

Lmk if you have questions

**Comment by jelilat** [comment]
Hmm. This is weird

Can you please try again and let me know if you face the same issue?

I implemented the same filter with your address and got results.

<img width="851" alt="Screenshot 2022-11-20 at 14 56 51" src="https://user-images.githubusercontent.com/23613565/202906324-5e1a0d6b-7194-48a6-be1e-680b8322aaa6.png">

<img width="844" alt="Screenshot 2022-11-20 at 14 58 47" src="https://user-images.githubusercontent.com/23613565/202906327-173874a7-edcf-4543-bfdf-00dc83a85ba7.png">

**Comment by dydymoon** [comment]
Hum you right this time I got some results too

However just saw something weird, the winner I draw in the follower page didnt mirror the post, and I didnt double check before posting the announcement

**Comment by jelilat** [comment]
Did you click on View Followers before creating a prize draw?

The implementation doesn’t apply the filter until you click on “View Followers”. This is a loophole I should have fixed a long time ago but I forgot.

Apologies for that.

**Comment by dydymoon** [comment]
I think I did yes, since I had a list in the recipient

No worries I’ll do another one

Le dim. 20 nov. 2022 à 15:24, Jelilat Anofiu ***@***.***> a
écrit :

**Comment by dydymoon** [comment]
Just tried again and "view followers" is doing nothing in the followers
page, I clicked several times

**Comment by jelilat** [comment]
Can you please share a video?

**Comment by dydymoon** [comment]
My bad it just worked when taking the video (but I probably clicked like 20
times)

Just drawn a new one, verifying if this one meet everything now before
sharing

Le dim. 20 nov. 2022 à 15:47, Jelilat Anofiu ***@***.***> a
écrit :

**Comment by dydymoon** [comment]
It’s weird, the second one didn’t mirrored either: opoptoe.lens

**Comment by jelilat** [comment]
Yeah. That was probably because it was fetching the data. 

I’ll add a loader to make people know it’s fetching the data so that they don’t click multiple times

**Comment by dydymoon** [comment]
Yes maybe but even once the data checked, the winners picked didn’t met the
criteria twice

Le dim. 20 nov. 2022 à 16:12, Jelilat Anofiu ***@***.***> a
écrit :

**Comment by jelilat** [comment]
Hmm. That must be a bug then.

Will investigate

**Comment by dydymoon** [comment]
Ok thanks, I’ll wait for your feedback before announcing the winner

Le dim. 20 nov. 2022 à 16:39, Jelilat Anofiu ***@***.***> a
écrit :

**Comment by jelilat** [comment]
The issue has now been fixed. The Following and Follower filters should work correctly now

**Comment by dydymoon** [comment]
Awesome thanks a lot for your reactivity, I just made the new draw and it
worked perfectly 🙏🔥

Le lun. 21 nov. 2022 à 08:34, Jelilat Anofiu ***@***.***> a
écrit :
