### ISSUE TITLE
[Bug] Error when entering non-localized float into amount input-field

### ISSUE THREAD

**Issue by wottpal** [jelilat/lensdrop#2]
Hey, i'm Germany-based so the correct way to define floating point numbers in an input field is something like `0,2` (with comma). This also works, but if I try to enter the US-version (`0.2`) it errors. I think it would make sense to `parseFloat` the entered amount and check whether the input results in `NaN`.

<img width="984" alt="Screen Shot 2022-09-27 at 12 57 55" src="https://user-images.githubusercontent.com/3930150/192508171-fc7e0adc-2fff-4d0d-a509-b2bd5ee5a408.png">

**Comment by jelilat** [comment]
Thanks for reporting. This issue has now been fixed.

Please let me know if this or any other issue comes up again
